#!/bin/bash
ROOT=$OPENSHIFT_DATA_DIR
ESB_VERSION=4.7.0

echo Started job Yasas build.sh
echo OPENSHIFT_DATA_DIR = ${OPENSHIFT_DATA_DIR}
echo java location =  ${OPENSHIFT_DATA_DIR/java}
echo OPENSHIFT_DIY_IP = $OPENSHIFT_DIY_IP
echo OPENSHIFT_DIY_PORT = $OPENSHIFT_DIY_PORT



echo -e "\nwrapper.backend.type=PIPE" >> ${OPENSHIFT_DATA_DIR}esb/conf/wrapper.conf

echo Finished job Yasas build.sh

